name: intake-cesmle-dev
channels:
  - conda-forge
dependencies:
  - python=3.6
  - numpy
  - xarray
  - netcdf4
  - zarr
  - dask
  - distributed
  - autopep8
  - flake8
  - black
  - isort
  - pytest
  - coverage
  - pytest-cov
  - codecov
  - sphinx>=1.6
  - sphinx_rtd_theme
  - recommonmark 
  - numpydoc
  - nbsphinx
  - pandoc
  - ipykernel
  - six
  - pip:
    - sphinx_copybutton

