name: intake-cesm-dev
channels:
  - conda-forge
dependencies:
  - codecov
  - coverage
  - dask
  - distributed
  - netcdf4
  - numpy
  - pytest
  - pytest-cov
  - pytest-icdiff
  - python=3.6
  - xarray
  - pyyaml
  - zarr

