name: intake-cesm-dev
channels:
  - conda-forge
dependencies:
  - autopep8
  - black
  - codecov
  - coverage
  - dask
  - distributed
  - flake8
  - intake
  - intake-xarray
  - ipykernel
  - nbsphinx
  - netcdf4
  - numpy
  - numpydoc
  - pandoc
  - pytest
  - pytest-cov
  - pytest-icdiff
  - python=3.7
  - pyyaml
  - recommonmark 
  - sphinx_rtd_theme
  - sphinx>=1.6
  - xarray
  - pip:
    - sphinx_copybutton

